### ISSUE TITLE
Please be careful when resolving conflicts.

### ISSUE THREAD

**Issue by kcy1019** [KAIST-VCLAB/kaist_cs482_2016_team2#10]
Please... Read the code first.

**Comment by scvs-dream** [comment]
Sorry Did i made a mistake?

**Comment by scvs-dream** [comment]
I think we can still fix it. please just let me know which point I had make a mistake during merge process

**Comment by kcy1019** [comment]
Actually, it was a small part and I fixed that but I wrote this for the future.

**Comment by scvs-dream** [comment]
Sorry
